export const projects = [
    {
        id: 1,
        name: 'University Application Portal',
        type: 'Full-Stack Web App',
        mainImage: '/Screenshot_515.png',
        mainImageText: "The home page of the application",
        technologies: ['Java', 'Spring', 'MySQL', 'Hibernate', 'Redis', 'Apache Kafka', 'Liquibase', 'MiniO', 'Keycloak', 'React', 'TypeScript', 'Redux', 'MUI', 'Freemarker', 'JUnit', 'Mockito'],
        liveLink: 'https://example.com/project-two',
        description: 'A university portal for students to apply for programs and admins to manage applications and users.',
        additionalImages: [
            {src: '/Screenshot_511.png', text: 'Screenshot of the real-time analytics panel.'},
            {src: '/Screenshot_512.png', text: 'Screenshot of the real-time analytics panel.'},
            {src: '/Screenshot_505.png', text: 'Screenshot of the login page.'},
            {src: '/Screenshot_518.png', text: 'Screenshot of the register page. All fields are required.'},
            {
                src: '/Screenshot_510.png',
                text: 'Profile page screenshot. Users can edit details and download attached files.'
            },
            {src: '/Screenshot_507.png', text: 'Screenshot of the applying page. All fields are required.'},
            {src: '/Screenshot_508.png', text: 'Screenshot of the applying page translated to Bulgarian.'},
            {src: '/Screenshot_513.png', text: 'Screenshot of the real-time analytics panel.'},
            {src: '/Screenshot_514.png', text: 'Screenshot of the real-time analytics panel.'},
            {
                src: '/Screenshot_504.png',
                text: 'Screenshot of admin dashboard. It tracks every action made for the applications.'
            },
            {src: '/Screenshot_506.png', text: 'Screenshot of the real-time analytics panel.'},
            {src: '/Screenshot_516.png', text: 'Screenshot of the real-time analytics panel.'},
            {src: '/Screenshot_517.png', text: 'Screenshot of the real-time analytics panel.'},
            {src: '/Screenshot_509.png', text: 'Screenshot of the real-time analytics panel.'},
        ],
    },
    {
        id: 2,
        name: 'Auto Show Website',
        type: 'Full-Stack Web App',
        mainImage: '/Screenshot_391.png',
        mainImageText: "The home page of the application",
        technologies: ['Java', 'Spring', 'MySQL', 'Hibernate', 'Thymeleaf', 'JavaScript', 'jQuery', 'HTML5', 'CSS3', 'Apache Maven', 'JWT'],
        liveLink: 'https://example.com/project-one',
        description: 'An auto show website for exploring detailed car info and interactive 3D models in a virtual showroom.',
        additionalImages: [
            {src: '/Screenshot_386.png', text: 'Screenshot showing the main dashboard interface.'},
            {src: '/Screenshot_387.png', text: 'Screenshot highlighting the user profile section.'},
            {src: '/Screenshot_389.png', text: 'Screenshot highlighting the user profile section.'},
            {src: '/Screenshot_392.png', text: 'Screenshot highlighting the user profile section.'},
            {src: '/Screenshot_390.png', text: 'Screenshot highlighting the user profile section.'},
            {src: '/Screenshot_388.png', text: 'Screenshot highlighting the user profile section.'},
            {src: '/Screenshot_395.png', text: 'Screenshot highlighting the user profile section.'},
            {src: '/Screenshot_396.png', text: 'Screenshot highlighting the user profile section.'},
            {src: '/Screenshot_397.png', text: 'Screenshot highlighting the user profile section.'},
            {src: '/Screenshot_398.png', text: 'Screenshot highlighting the user profile section.'},
            {src: '/Screenshot_399.png', text: 'Screenshot highlighting the user profile section.'},
            {src: '/Screenshot_400.png', text: 'Screenshot highlighting the user profile section.'},
            {src: '/Screenshot_403.png', text: 'Screenshot highlighting the user profile section.'},
            {src: '/Recently-Viewed-Cars.png', text: 'Screenshot highlighting the user profile section.'},
        ],
    },
    {
        id: 3,
        name: 'Weather Application',
        type: 'Desktop Application',
        mainImage: '/Screenshot_482.png',
        mainImageText: "The main page of the application",
        technologies: ['Java', 'JavaFX', 'Weather API', 'CSS3', 'Apache Maven', 'JUnit', 'Mockito'],
        liveLink: 'https://example.com/project-three',
        description: 'A desktop application for exploring real-time weather information and 7-day forecasts worldwide.',
        additionalImages: [
            {src: '/Screenshot_483.png', text: 'Screenshot of the API management dashboard.'},
            {src: '/Screenshot_484.png', text: 'Screenshot of the error tracking feature.'},
            {src: '/Screenshot_485.png', text: 'Screenshot of the error tracking feature.'},
            {src: '/Screenshot_486.png', text: 'Screenshot of the error tracking feature.'},
        ],
    },
];